spring.docker.compose.enabled=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/gameboard}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:gameboard}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:gameboard}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
